title: Community and Technology
author: tushabe
email: aaron.tushabe@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is a github landing page for my blog 

# social links
twitter_username: aarontushabe
github_username:  tushabe

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
